export const ROUTES = {
  login: '/login',
  candidate: {
    root: '/dashboard',
    dashboard: '/dashboard',
    cv: '/dashboard/cv',
    jobs: '/dashboard/jobs',
    applications: '/dashboard/applications',
    matching: '/dashboard/matching',
    coaching: '/dashboard/coaching',
    formations: '/dashboard/formations',
    coaches: '/dashboard/coaches',
    messages: '/dashboard/messages',
    resources: '/dashboard/resources',
    subscriptions: '/dashboard/subscriptions',
    profile: '/dashboard/profile',
  },
  coach: {
    root: '/coach',
    agreement: '/coach-agreement',
    dashboard: '/coach',
    candidates: '/coach/candidates',
    formations: '/coach/formations',
    sessions: '/coach/sessions',
    messages: '/coach/messages',
    resources: '/coach/resources',
    profile: '/coach/profile',
  },
} as const
